### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by BenFRC5147** [brayden-dowson/TheRiptide#1]
Yo what up, the readme for were to put Maps is incorrect, at least for CedMod EXILED though I doubt it makes a diff

it should be "/CedModEvents/Traitor Among Us Event/Maps"
instead of "/CedModEvents/TraitorAmongUs/Maps"

and "SlocLoader/Objects" should be "slocLoader/Objects"

**Comment by brayden-dowson** [comment]
Alright should be all fixed
